# Generated by Django 5.2.1 on 2025-05-16 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="ContactoMensaje",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("asunto", models.CharField(max_length=200)),
                ("mensaje", models.TextField()),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("leido", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Mensaje de Contacto",
                "verbose_name_plural": "Mensajes de Contacto",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Noticia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=200)),
                ("contenido", models.TextField()),
                ("fecha_publicacion", models.DateTimeField(default=django.utils.timezone.now)),
                ("imagen", models.ImageField(blank=True, null=True, upload_to="noticias/")),
            ],
            options={
                "verbose_name": "Noticia",
                "verbose_name_plural": "Noticias",
                "ordering": ["-fecha_publicacion"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=100)),
                ("nivel", models.CharField(choices=[("principiante", "Principiante"), ("intermedio", "Intermedio"), ("avanzado", "Avanzado")], max_length=20)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=6)),
                ("duracion_meses", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Planes",
            },
        ),
        migrations.CreateModel(
            name="Testimonio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=100)),
                ("rol", models.CharField(max_length=100)),
                ("contenido", models.TextField()),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("imagen", models.ImageField(blank=True, null=True, upload_to="testimonios/")),
            ],
            options={
                "verbose_name": "Testimonio",
                "verbose_name_plural": "Testimonios",
            },
        ),
    ]
