# Generated by Django 5.2.1 on 2025-05-17 01:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appComunidad", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("fecha_creacion", models.DateTimeField(default=django.utils.timezone.now)),
                ("imagen", models.ImageField(blank=True, null=True, upload_to="cursos/")),
                ("activo", models.BooleanField(default=True)),
                ("nivel_plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cursos", to="appComunidad.plan")),
                ("profesor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cursos_creados", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Leccion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("contenido", models.TextField()),
                ("numero_orden", models.PositiveIntegerField()),
                ("fecha_creacion", models.DateTimeField(default=django.utils.timezone.now)),
                ("duracion_minutos", models.PositiveIntegerField(default=30)),
                ("curso", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lecciones", to="appProfesores.curso")),
            ],
            options={
                "verbose_name": "Lección",
                "verbose_name_plural": "Lecciones",
                "ordering": ["curso", "numero_orden"],
                "unique_together": {("curso", "numero_orden")},
            },
        ),
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("puntaje_maximo", models.PositiveIntegerField(default=100)),
                ("fecha_creacion", models.DateTimeField(default=django.utils.timezone.now)),
                ("leccion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evaluaciones", to="appProfesores.leccion")),
            ],
            options={
                "verbose_name": "Evaluación",
                "verbose_name_plural": "Evaluaciones",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("tipo", models.CharField(choices=[("documento", "Documento"), ("video", "Video"), ("audio", "Audio"), ("presentacion", "Presentación"), ("ejercicio", "Ejercicio")], max_length=20)),
                ("archivo", models.FileField(upload_to="materiales/")),
                ("fecha_subida", models.DateTimeField(default=django.utils.timezone.now)),
                ("leccion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="materiales", to="appProfesores.leccion")),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materiales",
                "ordering": ["leccion", "fecha_subida"],
            },
        ),
        migrations.CreateModel(
            name="PerfilProfesor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("foto", models.ImageField(default="default_profile.png", upload_to="perfil_profesores/")),
                ("biografia", models.TextField()),
                ("especialidad", models.CharField(max_length=100)),
                ("anos_experiencia", models.PositiveIntegerField(default=0)),
                ("titulo_academico", models.CharField(blank=True, max_length=200, null=True)),
                ("usuario", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="perfil_profesor", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Perfil de Profesor",
                "verbose_name_plural": "Perfiles de Profesores",
            },
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enunciado", models.TextField()),
                ("tipo", models.CharField(choices=[("opcion_multiple", "Opción Múltiple"), ("verdadero_falso", "Verdadero/Falso"), ("texto_libre", "Texto Libre"), ("completar", "Completar")], max_length=20)),
                ("puntaje", models.PositiveIntegerField(default=10)),
                ("evaluacion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="preguntas", to="appProfesores.evaluacion")),
            ],
            options={
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
            },
        ),
        migrations.CreateModel(
            name="Opcion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("texto", models.CharField(max_length=200)),
                ("es_correcta", models.BooleanField(default=False)),
                ("pregunta", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="opciones", to="appProfesores.pregunta")),
            ],
            options={
                "verbose_name": "Opción",
                "verbose_name_plural": "Opciones",
            },
        ),
    ]
