# Generated by Django 5.2.1 on 2025-05-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProfesores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='perfilprofesor',
            name='titulo_academico',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
