"""
Django settings for comunidad_educativa project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
# In production, use environment variables or a secrets manager

# Use environment variable or generate a random key for development
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG to False to test 404 page in development
# Remember to set this to False in production
DEBUG = True  # Cambiado a True para desarrollo

# Host/domain names that this Django site can serve
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Custom 404 page handler
handler404 = 'comunidad_educativa.views.handler404'
handler500 = 'comunidad_educativa.views.handler500'

# Configuración de CORS
CORS_ALLOW_ALL_ORIGINS = True  # Solo para desarrollo
CORS_ALLOW_CREDENTIALS = True

# Configuración de CSRF
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "http://127.0.0.1:56335",  # Puerto del proxy del navegador de vista previa
    "http://localhost:56335",   # Puerto del proxy del navegador de vista previa
    "http://127.0.0.1:52191",   # Puerto del proxy del navegador de vista previa
    "http://localhost:52191",    # Puerto del proxy del navegador de vista previa
]

# Configuración de sesión
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = False  # Cambiar a True en producción con HTTPS
CSRF_COOKIE_SECURE = False    # Cambiar a True en producción con HTTPS

ALLOWED_HOSTS = ["*"]  # En producción, especifica los dominios permitidos

# Custom error handlers
# La configuración de DEBUG se maneja al inicio del archivo
# Los manejadores de error están configurados en urls.py

# Application definition
INSTALLED_APPS = [
    # Deben ir primero
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    # Aplicaciones estándar de Django
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    # Aplicaciones personalizadas
    'comunidad_educativa.apps.ComunidadEducativaConfig',
    'appComunidad',
    'appEstudiantes',
    'appProfesores',
    # Otras aplicaciones de terceros
    'widget_tweaks',
    # 'crispy_forms',
    # 'crispy_bootstrap4',
]

# Configuración de Admin Interface
X_FRAME_OPTIONS = 'SAMEORIGIN'
SILENCED_SYSTEM_CHECKS = ['security.W019']

# Tema claro por defecto
ADMIN_INTERFACE_THEME = 'default'
# O puedes elegir otros temas como: 'dark', 'light', 'modern', 'ocean', 'solar', 'summer', 'spring', 'winter', 'autumn', 'violet'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # Debe estar antes de CommonMiddleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "comunidad_educativa.urls"

# Configuración personalizada del sitio
SITE_NAME = "Comunidad Educativa"
SITE_HEADER = "Panel de Administración"
SITE_TITLE = "Sistema de Gestión Educativa"
INDEX_TITLE = "Bienvenido al Panel de Control"
SITE_URL = "/"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            BASE_DIR / "templates/admin",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "appComunidad.context_processors.user_redirect_processor",
                "comunidad_educativa.context_processors.admin_site_info",
            ],
            "builtins": [
                "appEstudiantes.templatetags.custom_filters",
            ],
            'libraries': {
                'admin_modify': 'django.contrib.admin.templatetags.admin_modify',
                'admin_urls': 'django.contrib.admin.templatetags.admin_urls',
            },
        },
    },
]

WSGI_APPLICATION = "comunidad_educativa.wsgi.application"

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
LANGUAGE_CODE = "es-es"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication settings
LOGIN_REDIRECT_URL = "appComunidad:index"
LOGOUT_REDIRECT_URL = "appComunidad:index"
LOGIN_URL = "login"

# Configuración de Crispy Forms (requiere django-crispy-forms)
