# Generated by Django 5.2.1 on 2025-05-17 01:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha_inscripcion", models.DateTimeField(default=django.utils.timezone.now)),
                ("completado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciones",
            },
        ),
        migrations.CreateModel(
            name="MaterialDescargado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha_descarga", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Material Descargado",
                "verbose_name_plural": "Materiales Descargados",
            },
        ),
        migrations.CreateModel(
            name="PerfilEstudiante",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("foto", models.ImageField(default="default_profile.png", upload_to="perfil_estudiantes/")),
                ("biografia", models.TextField(blank=True, null=True)),
                ("fecha_inscripcion", models.DateTimeField(default=django.utils.timezone.now)),
                ("idioma_nativo", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ProgresoLeccion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completado", models.BooleanField(default=False)),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Progreso de Lección",
                "verbose_name_plural": "Progreso de Lecciones",
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contenido", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("estudiante", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comentarios", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
                "ordering": ["-fecha"],
            },
        ),
    ]
