# Generated by Django 5.2.1 on 2025-05-17 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appComunidad", "0001_initial"),
        ("appEstudiantes", "0001_initial"),
        ("appProfesores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="leccion",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comentarios", to="appProfesores.leccion"),
        ),
        migrations.AddField(
            model_name="inscripcion",
            name="curso",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="estudiantes_inscritos", to="appProfesores.curso"),
        ),
        migrations.AddField(
            model_name="inscripcion",
            name="estudiante",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inscripciones", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="materialdescargado",
            name="estudiante",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="materiales_descargados", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="materialdescargado",
            name="material",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="descargas", to="appProfesores.material"),
        ),
        migrations.AddField(
            model_name="perfilestudiante",
            name="plan",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="appComunidad.plan"),
        ),
        migrations.AddField(
            model_name="perfilestudiante",
            name="usuario",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="perfil_estudiante", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="progresoleccion",
            name="estudiante",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="progreso_lecciones", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="progresoleccion",
            name="leccion",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="progreso_estudiantes", to="appProfesores.leccion"),
        ),
        migrations.AlterUniqueTogether(
            name="inscripcion",
            unique_together={("estudiante", "curso")},
        ),
        migrations.AlterUniqueTogether(
            name="materialdescargado",
            unique_together={("estudiante", "material")},
        ),
        migrations.AlterUniqueTogether(
            name="progresoleccion",
            unique_together={("estudiante", "leccion")},
        ),
    ]
