# Generated by Django 5.2.1 on 2025-05-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEstudiantes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilestudiante',
            name='biografia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='perfilestudiante',
            name='idioma_nativo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='progresoleccion',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
    ]
